@BASE_URL = http://localhost:5000

### Register user
POST {{BASE_URL}}/api/users/register HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email":"test@email.com",
    "password":"test1234",
    "password2":"test1234"
}

### Login user
POST {{BASE_URL}}/api/users/login HTTP/1.1
content-type: application/json

{
    "email":"test@email.com",
    "password":"test1234"
}

### Refresh token
POST {{BASE_URL}}/api/users/token HTTP/1.1
content-type: application/json

{
    "token":""
}

### Logout user
DELETE {{BASE_URL}}/api/users/logout HTTP/1.1
content-type: application/json

{
    "token":""
}

### GET Dashboard when token is valid
GET {{BASE_URL}}/api/dashboard HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOGZmM2QyMjM3Y2RhNzM2ZDFjNGZiNCIsIm5hbWUiOiJ0ZXN0IiwiaWF0IjoxNTg2NDkyNDI1LCJleHAiOjE1ODY0OTI3MjV9.yseulDNub8E9kw9SWWmvAfxfhbV8sWonoeS1Os72g8o
