@BASE_URL = http://localhost:5000

### Register user
POST {{BASE_URL}}/api/users/register HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email":"test@email.com",
    "password":"test1234",
    "password2":"test1234"
}

### Login user
POST {{BASE_URL}}/api/users/login HTTP/1.1
content-type: application/json

{
    "email":"test@test.com",
    "password":"test1234"
}

### Refresh token
POST {{BASE_URL}}/api/users/token HTTP/1.1
content-type: application/json

{
    "token":""
}

### Logout user
DELETE {{BASE_URL}}/api/users/logout HTTP/1.1
content-type: application/json

{
    "token":""
}

### GET Dashboard when token is valid
GET {{BASE_URL}}/api/dashboard HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOTU3MzZlNGE0MTRkMjgxMTAyMzVmMCIsIm5hbWUiOiJnYWJyaWVsZSIsImlhdCI6MTU4Njg1OTcyOSwiZXhwIjoxNTg2ODYwMDI5fQ.ZaEBOBxFqk1NxGcLtHmm1l9N-TBEMHGmj524gGuHGco
