@BASE_URL = http://localhost:5000

### Register user
POST {{BASE_URL}}/api/users/register HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email":"test@email.com",
    "password":"test1234"
}

### Login user
POST {{BASE_URL}}/api/users/login HTTP/1.1
content-type: application/json

{
    "email":"test@email.com",
    "password":"test1234"
}

### GET Dashboard when token is valid
GET {{BASE_URL}}/api/dashboard HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOGVjOTE2YmI4NjJlNDYwZGFhMmY1MCIsIm5hbWUiOiJ0ZXN0IiwiaWF0IjoxNTg2NDIzMzAzLCJleHAiOjE1ODY0MjM5MDN9.2mWhvRrQW3GIXGKG0ULw3rO8mYqDyrcC_yWsfZg-tJM
